### ISSUE TITLE
[BUG] Error on migration from v3 to v4 (mysql)

### ISSUE THREAD

**Issue by potatoru** [discord-tickets/migrate-v3-to-v4#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello! I have an issue while migrating to v4 mysql database.

```
The provided value for the column is too long for the column's type. Column: name
Migrating ticket 1108366718646095962...
prisma:error
Invalid `prisma.archivedRole.create()` invocation:
```

Then I manually increased the size of the `name` column to 1024 and everything works as expected (tried 255, but that's not enough).

Also this. Increased the size of the `name` column of `archivedChannels`.
```
The provided value for the column is too long for the column's type. Column: name
Error:
Invalid `prisma.ticket.create()` invocation:
```

### Expected Behavior

Expected no errors.

### Steps To Reproduce

Migrate from v3 to v4 mysql database.

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v18
- NPM: 9.5.1
- Bot: v4
```

**Comment by eartharoid** [comment]
Looks like this is because v3 encrypted role and channels names, while v4 does not.
I'll add decryption.

**Comment by eartharoid** [comment]
@potatoru please pull the latest changes, run `npm i` again and then run the script with `-k <encryption key>`.

**Comment by potatoru** [comment]
All good now! Thanks!
